### ISSUE TITLE
Checklist for release 3.8.0

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#180]
# MoodleBox – Release Checklist

## From 2 weeks to shortly before release

- [x] Create and edit the draft of the release on GitHub
- [x] Update `CHANGELOG.md` (same changes)
- [x] Commit the changes:
```
git add CHANGELOG.md
git commit -m "Update release notes for upcoming release x.y.z."
```

## Just before preparing the disk image

- [x] Update version date in `default.config.yml`
- [x] Update version of Moodle (branch) in `default.config.yml`, if needed
- [x] Update version of MoodleBox plugin in `default.config.yml`, if needed
- [x] Update version of MathJax in `default.config.yml`, if needed
- [x] Update version date in `CHANGELOG.md`, if needed
- [x] Update version number (can also be 'patch' or 'major' instead of 'minor'):
```
bumpversion minor --allow-dirty
```
- [x] Push: `git push`
- [x] Push tags: `git push --tags`

## Now do the real release work

- [x] Prepare and finalize the image

## Finally, publish the release and the disk image on GitHub

- [x] Edit and publish the release on GitHub
- [x] Upload disk image into the release's release page
- [x] Publish news on website and other media (Twitter, Moodle website, etc.)
